import PremiumPage from "@/components/page/premiumPage/PremiumPage";

import { Metadata } from "next";

export const metadata: Metadata = {
  title: "StreetGrub | Premium",
  description: "Generated by streetGrub Premium page",
};
const Premium = async () => {
  return (
    <div>
      <PremiumPage />
    </div>
  );
};

export default Premium;
