export const dynamic = "force-dynamic";

import Comments from "@/components/page/Dashboard/Comments";
import { getComments } from "@/services/commentService";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Food Book | Dashboard - Comments",
  description: "Generated by Food Book Dashboard - Comments page",
};
const Comment = async () => {
  const comments = await getComments();

  if (!comments?.data) {
    return <div>No comments found or failed to load.</div>;
  }
  return (
    <div>
      <Comments postComments={comments.data} />
    </div>
  );
};

export default Comment;
