import Categories from "@/components/page/home/Categories";
import Category from "@/components/page/home/Category";
import GoPremium from "@/components/page/home/GoPremium ";
import HeroSection from "@/components/page/home/hero/Hero";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "StreetFood | Home",
  description: "Generated by streetGrub Home page",
};

export default async function Home() {
  //   const res = await singleUserget();
  //   const Post = await getAllPostForGest();
  return (
    <div className="min-h-screen flex flex-col">
      <main className="flex-grow">
        <HeroSection />
        <div className=" max-w-7xl md:mx-auto mx-2 py-12">
          <Categories />
          {/* <FeaturedSpots posts={Post?.data} user={res.data} /> */}

          <Category />
          {/* <FoodSpotList /> */}
          <GoPremium />
        </div>
      </main>
    </div>
  );
}
