import ContactPage from "@/components/page/contact/ContactPage";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Food Book | Contact",
  description: "Generated by Food Book Contact page",
};
const Contact = () => {
  return (
    <div>
      <ContactPage />
    </div>
  );
};

export default Contact;
