import Users from "@/components/page/Dashboard/Users";
import { getAllusers } from "@/services/userService";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Food Book | Dashboard - Users",
  description: "Generated by Food Book Dashboard Users page",
};
const User = async () => {
  const result = await getAllusers();
  return (
    <div>
      <Users users={result?.data} />
    </div>
  );
};

export default User;
