import Categories from "@/components/page/Dashboard/Categories";
import { getAllCategory } from "@/services/categoryService";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Food Book | Dashboard - Category",
  description: "Generated by Food Book  Dashboard - Category page",
};
const Category = async () => {
  const result = await getAllCategory();

  return (
    <div>
      <Categories initialCategories={result?.data} />
    </div>
  );
};

export default Category;
