import Analytics from "@/components/page/Dashboard/Analytics";
import { analyticsOverview } from "@/services/AuthService";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Food Book | Dashbaord - Analytics",
  description: "Generated by Food Book  Dashbaord - Analytics page",
};
const Analytic = async () => {
  const result = await analyticsOverview();
  return (
    <div>
      <Analytics
        contentData={result?.data?.AnalyticsArray}
        visitorData={result?.data?.visitorData}
        categoryData={result?.data?.categoryData}
      />
    </div>
  );
};

export default Analytic;
