import AllPostPage from "@/components/AllPost/AllPostPage";
import { getAllCategory } from "@/services/categoryService";
import { getAllPost } from "@/services/postService";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Food Book | AllPost",
  description: "Generated by Food Book AllPost page",
};
const AllProduct = async () => {
  const { data } = await getAllPost();
  const { data: Categories } = await getAllCategory();
  return (
    <div>
      <AllPostPage posts={data} categoriess={Categories} />
    </div>
  );
};

export default AllProduct;
