import AllPostPage from "@/components/AllPost/AllPostPage";
import { getAllCategory } from "@/services/categoryService";
import { getAllPost } from "@/services/postService";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Food Book | AllPost",
  description: "Generated by Food Book AllPost page",
};
const AllProduct = async () => {
  
    const postRes = await getAllPost();
  const categoryRes = await getAllCategory();

  const data = postRes?.data ?? [];
  const Categories = categoryRes?.data ?? [];

  return (
    <div>
      <AllPostPage posts={data} categoriess={Categories} />
    </div>
  );
};

export default AllProduct;
